export const dummyProducts = [
	{
		id: '1',
		image: './assets/shirt-2.webp',
		title: 'Product 2',
		vendor: 'Vendor 2',
		price: '300',
		compare_at_price: '600',
		badge_text: 'Sale',
	},
	{
		id: '2',
		image: './assets/shirt-3.webp',
		title: 'Product 3',
		vendor: 'Vendor 3',
		price: '700',
		compare_at_price: '1400',
		badge_text: 'Exclusive',
	},
	{
		id: '3',
		image: './assets/shorts-4.webp',
		title: 'Product 4',
		vendor: 'Vendor 4',
		price: '200',
		compare_at_price: '400',
		badge_text: '',
	},
	{
		id: '4',
		image: './assets/shirt-1.webp',
		title: 'Product 1',
		vendor: 'Vendor 1',
		price: '500',
		compare_at_price: '1000',
		badge_text: 'New',
	},
];
